version: "3.7"
services:
  frontend:
    build: ./frontend/.
    image: h15t3r5im5/mini-project:frontend 
    deploy:
      replicas: 3
    ports: 
    - target: 5000 
      published: 5000
      protocol: tcp
  backend:
    build: ./backend/.
    image: h15t3r5im5/mini-project:backend
    deploy:
      replicas: 3 
    ports: 
    - target: 5001
      protocol: tcp