version: "3.7"
services:
  frontend:
    build: ./frontend/.
    image: hlistersims/mini-project:frontend 
    ports: 
    - target: 5000 
      published: 5000
      protocol: tcp
  backend:
    build: ./backend/.
    image: hlistersims/mini-project:backend 
    ports: 
    - target: 5001 
      published: 5001
      protocol: tcp